# Colors (Gruvbox Material Hard Dark)
# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black = '#32302f'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black = '#32302f'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'

[cursor]
blink_interval = 600
blink_timeout = 5
thickness = 0.15

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true

[colors]
draw_bold_text_with_bright_colors = true

[window]
startup_mode = "Maximized"

[window.padding]
x = 10
y = 0

[bell]
animation = "EaseOutCubic"
color = "#1e1e1e"
duration = 158
