# Everblush
# Default colors
[colors.primary]
background = '#141b1e'
foreground = '#dadada'

[colors.cursor]
text = '#dadada'
cursor = '#dadada'

# Normal colors
[colors.normal]
black = '#232a2d'
red = '#e57474'
green = '#8ccf7e'
yellow = '#e5c76b'
blue = '#67b0e8'
magenta = '#c47fd5'
cyan = '#6cbfbf'
white = '#b3b9b8'

# Bright colors
[colors.bright]
black = '#2d3437'
red = '#ef7e7e'
green = '#96d988'
yellow = '#f4d67a'
blue = '#71baf2'
magenta = '#ce89df'
cyan = '#67cbe7'
white = '#bdc3c2'

[cursor]
blink_interval = 645
blink_timeout = 5
thickness = 1.00

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "alacritty"

[font]
glyph_offset = { x = 1, y = 1 }
builtin_box_drawing = true

[colors]
draw_bold_text_with_bright_colors = true

[window]
startup_mode = "Maximized"
dynamic_padding = true

[window.padding]
x = 10
y = 0


[bell]
animation = "EaseOutCubic"
color = "#212121"
duration = 158
