[cursor]
blink_interval = 600
blink_timeout = 5
thickness = 0.15

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true

[colors]
draw_bold_text_with_bright_colors = true

[font.offset]
x = 0
y = 0

[window]
dynamic_title = true
startup_mode = "Maximized" 

[window.padding]
x = 10
y = 0

[bell]
animation = "EaseOutCubic"
color = "#1e1e1e"
duration = 158 
