# Material Darker
[colors.primary]
background = '#212121'
foreground = '#EEFFFF'

[colors.normal]
black = '#212121'
red = '#F07178'
green = '#C3E88D'
yellow = '#FFCB6B'
blue = '#82AAFF'
magenta = '#C792EA'
cyan = '#89DDFF'
white = '#EEFFFF'

[colors.bright]
black = '#303030'
red = '#F07178'
green = '#C3E88D'
yellow = '#FFCB6B'
blue = '#82AAFF'
magenta = '#C792EA'
cyan = '#89DDFF'
white = '#FFFFFF'

[colors.cursor]
text = '#212121'
cursor = '#EEFFFF'

[colors.selection]
text = '#EEFFFF'
background = '#4A4A4A'

[cursor]
blink_interval = 645
blink_timeout = 255
# thickness = 1.00

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
normal.family = "MesloLGSDZ Nerd Font"

[colors]
draw_bold_text_with_bright_colors = true

[window]
startup_mode = "Maximized"
dynamic_padding = true
decorations = "none"

[window.padding]
x = 10
y = 0

[keyboard]
# fix tmux sending C-BS as C-h
bindings = [{ key = "Backspace", mods = "Control", chars = "\u0017" }]
