[colors.primary]
foreground = "#EEEEEE"
background = "#000000"

[colors.cursor] 
text = "#303030"
cursor = "#EEEEEE"

[colors.normal]
black = "#1d1d1d"
red = "#c5152f"
green = "#c9d05c"
yellow = "#ffcc4b"
blue = "#b3deef"
magenta = "#d3b987"
cyan = "#73cef4"
white = "#EEEEEE"

[colors.bright]
black = "#323232"
red = "#f43753"
green = "#d9e066"
yellow = "#facc72"
blue = "#c0eafb"
magenta = "#efd093"
cyan = "#a1d6ec"
white = "#ffffff"
