#! /bin/sh

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
killall picom; picom -b --experimental-backends &
$HOME/.config/polybar/launch.sh --colorblocks & 
nitrogen --restore &
killall dunst; dunst & 
xdman &
#/usr/lib/polkit-kde-authentication-agent-1 & 
#/usr/lib/xfce-polkit/xfce-polkit &
#/usr/bin/polkit-dumb-agent &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#Color Settings
#bspc config focused_border_color "#e3ffff"
#bspc config normal_border_color "#420069"

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"



bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         3.5
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config ignore_ewmh_focus    true 
#bspc config focus_follows_pointer true 
#bspc config pointer_follows_focus true
bspc config external_rules_command ~/.config/bspwm/scripts/bspwm-external-rules

bspc rule -a Navigator:firefox desktop='^1'
bspc rule -a discord desktop='^2' follow=off focus=off
bspc rule -a Spotify:spotify desktop='^2'
bspc rule -a Steam desktop='^3'
bspc rule -a Lutris desktop='^3'
bspc rule -a Minecraft Launcher desktop='^3'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a kitty desktop='^4' follow=on focus=on
bspc rule -a Anydesk desktop='^7'
bspc rule -a Alacritty state=floating



