require("user.config.user_commands")
require("user.config.keymaps")
require("user.config.options")
require("user.config.autocmds")

vim.cmd("cnoreabbrev W! w!")
vim.cmd("cnoreabbrev W1 w!")
vim.cmd("cnoreabbrev Q1 q!")
vim.cmd("cnoreabbrev Q! q!")
vim.cmd("cnoreabbrev Qall! qall!")
vim.cmd("cnoreabbrev Wq wq")
vim.cmd("cnoreabbrev Wa wa")
vim.cmd("cnoreabbrev wQ wq")
vim.cmd("cnoreabbrev WQ wq")
vim.cmd("cnoreabbrev W w")
vim.cmd("cnoreabbrev Q q")
vim.loader.enable()
