#!/usr/bin/env fish
set pomo_options
set -a pomo_options work 45
set -a pomo_options lang 25
set -a pomo_options break 10
set -a pomo_options default 25

function find_pomo_options
    set --local index 1
    for key in $pomo_options
        if test $key = $argv[1]
            echo (math $index +1)
            return 0
        end
        set index (math $index + 1)
    end
    echo -1
    return 1
end


function pomodoro
    if test -z "$argv[1]"
        echo "Usage: pomodoro [work|lang|break]"
        return 1
    end
    set pomo_index_value_time $(find_pomo_options $argv[1])
    if test $pomo_index_value_time -gt 0
        timer "$pomo_options[$pomo_index_value_time]m"
        notify-send Pomodoro "Time to $pomo_options[$pomo_index_value_time]" --urgency="critical"
    else
        echo "Usage: pomodoro [work|lang|break]"
        return 1
    end
end

pomodoro $argv
