#!/bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1
eval $(/usr/bin/gnome-keyring-daemon --start)
redshift -m drm -PO 3000
export WLR_NO_HARDWARE_CURSORS=1
export WLR_RENDERER_ALLOW_SOFTWARE=1
export SSH_AUTH_SOCK
export QT_QPA_PLATFORMTHEME=gnome
export dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
export ZDOTDIR="$HOME/.config/zsh/"
exec Hyprland
