[[plugin.prepend_fetchers]]
id    = "mime"
url   = "local://*"
run   = "mime-ext.local"
prio  = "high"
group = "mime"

[[plugin.prepend_fetchers]]
id    = "mime"
url   = "remote://*"
run   = "mime-ext.remote"
prio  = "high"
group = "mime"

[preview]
wrap = "yes"
