return {
  { "akinsho/bufferline.nvim", enabled = false },
  { "catppuccin/nvim", name = "catppuccin", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "garymjr/nvim-snippets", enabled = false },
  { "hrsh7th/cmp-buffer", enabled = false },
  { "hrsh7th/cmp-path", enabled = false },
  { "lukas-reineke/headlines.nvim", enabled = false },
  { "mfussenegger/nvim-lint", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "saadparwaiz1/cmp_luasnip", enabled = false },
  { "windwp/nvim-ts-autotag", enabled = false },
}
