"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = 'night_owl'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
$conda\
$docker_context\
$cmd_duration\
$time\
$line_break\
$character"""

[fill]
symbol = " "

[os]
disabled = false
style = "bold sapphire"
format = "[$symbol ]($style)"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"

[username]
show_always = false
style_user = "bold sapphire"
style_root = "bold red"
format = "[$user]($style) "

[directory]
style = "bold lavender"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bold peach"
format = "[$symbol $branch]($style) "

[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style) "

[c]
symbol = ""
style = "bold green"
format = "[$symbol $version]($style) "

[rust]
symbol = ""
style = "bold peach"
format = "[$symbol $version]($style) "

[golang]
symbol = ""
style = "bold sapphire"
format = "[$symbol $version]($style) "

[nodejs]
symbol = ""
style = "bold green"
format = "[$symbol $version]($style) "

[bun]
symbol = ""
style = "bold peach"
format = "[$symbol $version]($style) "

[php]
symbol = ""
style = "bold lavender"
format = "[$symbol $version]($style) "

[java]
symbol = ""
style = "bold peach"
format = "[$symbol $version]($style) "

[kotlin]
symbol = ""
style = "bold lavender"
format = "[$symbol $version]($style) "

[haskell]
symbol = ""
style = "bold sapphire"
format = "[$symbol $version]($style) "

[python]
symbol = ""
style = "bold yellow"
format = "[$symbol $version( \\($virtualenv\\))]($style) "

[conda]
symbol = ""
style = "bold sapphire"
format = "[$symbol $environment]($style) "
ignore_base = false

[docker_context]
symbol = ""
style = "bold sapphire"
format = "[$symbol $context]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "bold overlay0"
format = "[ $time]($style)"

[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'
vimcmd_replace_one_symbol = '[❮](bold lavender)'
vimcmd_replace_symbol = '[❮](bold lavender)'
vimcmd_visual_symbol = '[❮](bold yellow)'

[cmd_duration]
show_milliseconds = true
format = "[ $duration]($style) "
style = "bold yellow"
disabled = false

[palettes.night_owl]
red = "#EF5350"
peach = "#F78C6C"
yellow = "#ECC48D"
green = "#ADDB67"
sapphire = "#82AAFF"
lavender = "#C792EA"
overlay0 = "#5F7E97"
crust = "#011627"

[palettes.light_owl]
red = "#DE3D3B"
peach = "#E64D49"
yellow = "#DAAA01"
green = "#08916A"
sapphire = "#288ED7"
lavender = "#994CC3"
overlay0 = "#93A1A1"
crust = "#FBFBFB"
