local M = {}

M.servers = {
	"tsserver",
	"bashls",
	"lua_ls",
	"pyright",
	"gopls",
	"tailwindcss",
	"eslint",
	"svelte",
	"marksman",
	"html",
	"rust_analyzer",
	"cssls",
	"cssmodules_ls",
	"clangd",
	"jsonls",
}

M.icons = {
	kinds = {
		cmp_kinds = {
			Text = " ",
			Method = "  ",
			Function = "  ",
			Constructor = "  ",
			Field = "  ",
			Variable = "  ",
			Class = "  ",
			Interface = "  ",
			Module = "  ",
			Property = "  ",
			Unit = "  ",
			Value = "  ",
			Enum = "  ",
			Keyword = "  ",
			Snippet = "  ",
			Color = "  ",
			File = "  ",
			Reference = "  ",
			Folder = "  ",
			EnumMember = "  ",
			Constant = "  ",
			Struct = "  ",
			Event = "  ",
			Operator = "  ",
			TypeParameter = "  ",
		},
		--   פּ ﯟ   some other good icons
		kind_icons = {
			Array = "",
			Boolean = "",
			Text = "",
			Method = "",
			Function = "",
			Constructor = "",
			Field = "",
			Variable = "",
			Class = "ﴯ",
			Interface = "",
			Module = "",
			Null = "ﳠ",
			Property = "ﰠ",
			Unit = "",
			Value = "",
			Enum = "",
			Key = "",
			Keyword = "",
			Snippet = "",
			Package = "",
			Color = "",
			File = "",
			Reference = "",
			Folder = "",
			EnumMember = "",
			Constant = "",
			Struct = "",
			Object = "",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
		lvim_kind = {
			Array = "",
			Boolean = "",
			Class = "",
			Color = "",
			Constant = "",
			Constructor = "",
			Enum = "",
			EnumMember = "",
			Event = "",
			Field = "",
			File = "",
			Folder = "",
			Function = "",
			Interface = "",
			Key = "",
			Keyword = "",
			Method = "",
			Module = "",
			Namespace = "",
			Null = "ﳠ",
			Number = "",
			Object = "",
			Operator = "",
			Package = "",
			Property = "",
			Reference = "",
			Snippet = "",
			String = "",
			Struct = "",
			Text = "",
			TypeParameter = "",
			Unit = "",
			Value = "",
			Variable = "",
		},
		codicons = {
			Text = "",
			Method = "",
			Function = "",
			Constructor = "",
			Field = "",
			Variable = "",
			Class = "",
			Interface = "",
			Module = "",
			Property = "",
			Unit = "",
			Value = "",
			Enum = "",
			Keyword = "",
			Snippet = "",
			Color = "",
			File = "",
			Reference = "",
			Folder = "",
			EnumMember = "",
			Constant = "",
			Struct = "",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
		icons_icons = {
			Text = "",
			Method = "m",
			Function = "",
			Constructor = "",
			Field = "",
			Variable = "",
			Class = "",
			Interface = "",
			Module = "",
			Property = "",
			Unit = "",
			Value = "",
			Enum = "",
			Keyword = "",
			Snippet = "",
			Color = "",
			File = "",
			Reference = "",
			Folder = "",
			EnumMember = "",
			Constant = "",
			Struct = "",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
		icons = {
			Text = " ",
			Method = " ",
			Function = " ",
			Constructor = "⌘ ",
			Field = "ﰠ ",
			Variable = " ",
			Class = "ﴯ ",
			Interface = " ",
			Module = " ",
			Property = "ﰠ ",
			Unit = "塞",
			Value = " ",
			Enum = " ",
			Keyword = "廓",
			Snippet = " ",
			Color = " ",
			File = " ",
			Reference = " ",
			Folder = " ",
			EnumMember = " ",
			Constant = " ",
			Struct = "פּ ",
			Event = " ",
			treesitter = "",
			Operator = " ",
			TypeParameter = "",
		},
	},
	ui = {
		file = "",
		files = "",
		folder = "",
		folders = "",
		open_folder = "",
		empty_folder = "",
		project_folder = "",
		buffers = "",
		restore = "",
		config = "",
		close = "",
		buffer_close = "",
		modified_buffer = "●",
		arrow_right_out = "󰧂",
		arrow_right = "",
		arrow_left = "",
		arrow_left_out = "󰧀",
		double_chevron = "󰄾",
		chevron = "",
		lsp_error = " ",
		lsp_warn = " ",
		lsp_hint = " ",
		lsp_info = " ",
		powerline_round = "",
		powerline_square = " ",
		mode_icon = "",
		modified = " ",
		prompt_prefix = " ",
		selection_caret = " ",
	},
	git = {
		git = " ",
		add = " ",
		change = " ",
		delete = " ",
		unstaged = "● ",
		modified = "  ",
		renamed = " ",
		ignored = "◌",
		conflict = "",
		staged = "S",
		untracked = "U",
	},
}

return M
