local opt = vim.opt
local g = vim.g

opt.backup = false -- disable backup
opt.clipboard = "" -- disable system clipboard
opt.colorcolumn = "80"
opt.inccommand = "split" -- inc in split view
opt.jumpoptions = "stack,view"
opt.mouse = "a" -- disable mouse support
opt.pumblend = 0 -- popup menu blend
opt.pumheight = 15 -- pop up menu height
opt.relativenumber = false -- disable relative number
opt.scrolloff = 8 -- Lines of context
opt.sidescrolloff = 8 -- Columns of context
opt.spelllang = { "en", "pt_br" } -- spellang
opt.swapfile = false -- disable swapfile
opt.undofile = true -- enable persistent undo
opt.writebackup = false -- disable backup
g.markdown_folding = 1 -- enable markdown folding
g.lazyvim_python_lsp = "basedpyright" -- basedpyright as python lsp
g.lazyvim_picker = "telescope" -- use telescope as picker
g.autoformat = false -- disable LazyVim auto format
